FROM mcr.microsoft.com/azure-functions/powershell:4-powershell7.2
ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

COPY . /home/site/wwwroot
